### PR TITLE
Change structure as proposed in #3

### LINKED ISSUE #3: Reuse test scripts for multiple inputs + expected outputs
Since we have these elaborate test scripts it would be nice to be able to reuse them for multiple inputs and expected outputs. Maybe with a folder structure similar to this, the test script could just iterate over the inputs, or get an index as an additional parameter.
```
├── inputs
│   ├── input-1
│   ├── input-2
│   └── input-3
├── expected.outputs
│   ├── expected.output-1
│   ├── expected.output-2
│   └── expected.output-3
├── outputs
│   ├── output-1
│   ├── output-2
│   └── output-3
├── names
│   ├── name-1
│   ├── name-2
│   └── name-3
└── secrets
    ├── secret-1
    ├── secret-2
    └── secret-3
```

### PR DESCRIPTION
**Pull request by tAq5Z6eE**
Closes #3 
- [x] Implemented for task-1
- [x] Implemented for task-2

The `common_tests` folder contains a list of input/output comparison tests. The scripts auto-discover new tests following the given naming scheme of `test-$n`.

The folder structure changed:
The script can now be called as `./task-$k/test-task-$k.sh task-$k/ PATH_TO_OWN_PROJECT/task-$k [PATH_TO_ORACLE]` with `$k ∈ {1,2}`.

### CODE REVIEW

**Comment by Mat2095** [comment]
Why do we need `expected.output` and `output`, that contain the same data? Same question could be asked about `secret.code` and `secret`, but that was already the case before.

**Comment by tAq5Z6eE** [comment]
We need both `secret.code` and `secret` as the first one might contain longer/shorter input to then be able to check if the program correctly interprets the code as `secret` shortened/elongated to four  digits.

`output` should probably not be there as it is auto-generated by the tests and I accidentally added it to the commit.

**Comment by Mat2095** [comment]
Ah, the `secret`-file is only used for task 2, but not for task 1. Didn't notice that.

**Comment by Mat2095** [comment]
I guess the folder `task-1/test01` including its content should not be needed any more?

**Comment by Mat2095** [comment]
If I could approve this PR, I would ;)

**Comment by alessiogambi** [comment]
@pirak I suspect we are working on the same issue: restructuring the organization of the tests.
But i also see that you are committing additional public tests as well? I would suggest you commit the new public tests into separated pull request.

**Comment by alessiogambi** [comment]
@pirak I'll go on and my own merge request, then I'll try to include your changes as well. The issue I see with your implementation is that if a student wants to (re)run a single test this does not seem to be possible. Sorry.

**Comment by tAq5Z6eE** [comment]
Running a single test should be fairly easy implementable by an additional optional parameter specifying the number of the test and then setting both the lower and upper bounds of the used for each sequence to the given parameter.

**Pull request closed without merging**
